1 Start the local cluster

ipcluster start -n 3 

2 Add more computation engine using the ipengine command

ipengine --profile=remote

First, we start a cluster with 3 engines

In [1]:
import ipyparallel as ipp
import numpy as np
c = ipp.Client()
print(c.ids)

[0, 1, 2]


Now, start more engines! 
ipengine 

In [2]:
c = ipp.Client()
print(c.ids)

[0, 1, 2, 3]


We have now 4 engines!

In [3]:
c = ipp.Client()
print(c.ids)

[0, 1, 2, 3, 5]


In [4]:
dview = c[:]
dview.scatter('a',np.arange(28,dtype='float'))

<AsyncResult: scatter>

In [5]:
dview['a']

[array([0., 1., 2., 3., 4., 5.]),
 array([ 6.,  7.,  8.,  9., 10., 11.]),
 array([12., 13., 14., 15., 16., 17.]),
 array([18., 19., 20., 21., 22.]),
 array([23., 24., 25., 26., 27.])]