In [1]:
import ipyparallel as ipp
import numpy as np
c = ipp.Client(profile='mpi3', cluster_id='mpi3')
print(c.ids)
dview = c[:]

[0, 1, 2, 3, 4]


In [2]:
dview.scatter('a',np.arange(32,dtype='float64'))

<AsyncResult: scatter>

In [3]:
dview['a']

[array([0., 1., 2., 3., 4., 5., 6.]),
 array([ 7.,  8.,  9., 10., 11., 12., 13.]),
 array([14., 15., 16., 17., 18., 19.]),
 array([20., 21., 22., 23., 24., 25.]),
 array([26., 27., 28., 29., 30., 31.])]

In [4]:
# run the contents of the file on each engine:
dview.run('psum.py')

<AsyncResult: execute>

In [5]:
%px totalsum = psum(a)

In [6]:
dview['totalsum']

[array(496.), array(496.), array(496.), array(496.), array(496.)]

In [7]:
dview.run('rank_mpi.py')

<AsyncResult: execute>

In [8]:
%px totalrank = myrank()

In [9]:
dview['totalrank']

[0, 1, 2, 3, 4]

In [10]:
%px totalhost = hostname()

In [11]:
dview['totalhost']

['DESKTOP-10711',
 'DESKTOP-10711',
 'DESKTOP-10711',
 'DESKTOP-10711',
 'DESKTOP-10711']

In [12]:
%px totalpid = mypid()

In [13]:
dview['totalpid']

[3260, 6048, 20124, 10388, 7332]

In [14]:
%px mysendOneToZero()

Out[0:10]: True

Out[1:10]: True

Out[2:10]: True

Out[3:10]: True

Out[4:10]: True

In [15]:
dview['d']

[array([7.]), array([0.]), array([0.]), array([0.]), array([0.])]

In [16]:
dview.run('mpi1_py/blocking_send.py')

<AsyncResult: execute>

In [17]:
dview['bb']

[array([3]), array([3]), array([0]), array([0]), array([0])]

In [18]:
f = open('mpi_IO', 'rb')
a = np.fromfile(f, dtype=np.int)
print(a)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3]
